changelog:
  categories:
    - title: Changes
      exclude:
        labels:
          - dependencies
    - title: 📦 npm Dependencies
      labels:
        - dependencies
        - npm
    - title: 📦 GitHub Actions Dependencies
      labels:
        - dependencies
        - github-actions
    - title: 📦 Other Dependencies
      labels:
        - dependencies
