name: Tag on New Issue

on:
  issues:
    types: [opened]

permissions: 
    contents: read

jobs:
  tag-user:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
        with:
          egress-policy: audit

      - name: Tag user on new issue
        uses: devops-actions/issue-comment-tag@3a605c5f21e15e5b963c866421bf4189bcc32310 # v0.1.10
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          team: ${{ vars.TAG_USER }}
          issue: ${{ github.event.issue.number }}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.repository }}
