name: Tag on New Issue

on:
  issues:
    types: [opened]

permissions: 
    contents: read

jobs:
  tag-user:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - name: Tag user on new issue
        uses: devops-actions/issue-comment-tag@3a605c5f21e15e5b963c866421bf4189bcc32310 # v0.1.10
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          team: ${{ vars.TAG_USER }}
          issue: ${{ github.event.issue.number }}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.repository }}
